name: Release Version
on:
  release:
    types:
      - published
permissions:
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker Image
        run: docker build -t cardanofoundation/cf-product-tracing-aggregator:${{ github.event.release.tag_name }}  .
      - name: Push Docker Image
        run: docker push cardanofoundation/cf-product-tracing-aggregator:${{ github.event.release.tag_name }}